
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.expertedge.entrustplugin.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2018-06-21T22:11:01.655+01:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "EntrustMultiFactorAuthImplService",
                      portName = "EntrustMultiFactorAuthImplPort",
                      targetNamespace = "http://ws.entrustplugin.expertedge.com/",
                      wsdlLocation = "file:/C:/Users/waliu.faleye/Documents/workspace-sts-3.8.2.RELEASE/consolidatedapps/src/main/resources/entrust.wsdl",
                      endpointInterface = "com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl")
                      
public class EntrustMultiFactorAuthImplImpl implements EntrustMultiFactorAuthImpl {

    private static final Logger LOG = Logger.getLogger(EntrustMultiFactorAuthImplImpl.class.getName());

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performActivateCompleteSoftToken(com.expertedge.entrustplugin.ws.ActivateCompleteSoftTokenDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.ActivateCompleteSoftTokenResponseDTO performActivateCompleteSoftToken(com.expertedge.entrustplugin.ws.ActivateCompleteSoftTokenDTO arg0) { 
        LOG.info("Executing operation performActivateCompleteSoftToken");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.ActivateCompleteSoftTokenResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performDeactivateToken(com.expertedge.entrustplugin.ws.TokenAdminDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performDeactivateToken(com.expertedge.entrustplugin.ws.TokenAdminDTO arg0) { 
        LOG.info("Executing operation performDeactivateToken");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performSetMutualAuth(com.expertedge.entrustplugin.ws.SetMutualSecretRespDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthMutResponseDTO performSetMutualAuth(com.expertedge.entrustplugin.ws.SetMutualSecretRespDTO arg0) { 
        LOG.info("Executing operation performSetMutualAuth");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthMutResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performTokenSync(com.expertedge.entrustplugin.ws.TokenSynDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performTokenSync(com.expertedge.entrustplugin.ws.TokenSynDTO arg0) { 
        LOG.info("Executing operation performTokenSync");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performOTPAuthentication(com.expertedge.entrustplugin.ws.OtpAuthDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performOTPAuthentication(com.expertedge.entrustplugin.ws.OtpAuthDTO arg0) { 
        LOG.info("Executing operation performOTPAuthentication");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performActivateToken(com.expertedge.entrustplugin.ws.TokenAdminDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performActivateToken(com.expertedge.entrustplugin.ws.TokenAdminDTO arg0) { 
        LOG.info("Executing operation performActivateToken");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performUpdateEntrustUser(com.expertedge.entrustplugin.ws.UserAdminDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performUpdateEntrustUser(com.expertedge.entrustplugin.ws.UserAdminDTO arg0) { 
        LOG.info("Executing operation performUpdateEntrustUser");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performCreateSoftToken(com.expertedge.entrustplugin.ws.CreateSoftTokenDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.CreateSoftTokenResponseDTO performCreateSoftToken(com.expertedge.entrustplugin.ws.CreateSoftTokenDTO arg0) { 
        LOG.info("Executing operation performCreateSoftToken");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.CreateSoftTokenResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performSetMutualAuthX(com.expertedge.entrustplugin.ws.SetMutualSecretXDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthMutResponseDTO performSetMutualAuthX(com.expertedge.entrustplugin.ws.SetMutualSecretXDTO arg0) { 
        LOG.info("Executing operation performSetMutualAuthX");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthMutResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performSetQA(com.expertedge.entrustplugin.ws.QaSetDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performSetQA(com.expertedge.entrustplugin.ws.QaSetDTO arg0) { 
        LOG.info("Executing operation performSetQA");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performTokenAuthNoCategory(com.expertedge.entrustplugin.ws.TokenAuthDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performTokenAuthNoCategory(com.expertedge.entrustplugin.ws.TokenAuthDTO arg0) { 
        LOG.info("Executing operation performTokenAuthNoCategory");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performAssignToken(com.expertedge.entrustplugin.ws.TokenAdminDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performAssignToken(com.expertedge.entrustplugin.ws.TokenAdminDTO arg0) { 
        LOG.info("Executing operation performAssignToken");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performCreateSendOTP(com.expertedge.entrustplugin.ws.OtpCreateSendDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performCreateSendOTP(com.expertedge.entrustplugin.ws.OtpCreateSendDTO arg0) { 
        LOG.info("Executing operation performCreateSendOTP");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performSoftTokenSync(com.expertedge.entrustplugin.ws.SoftTokenSynDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performSoftTokenSync(com.expertedge.entrustplugin.ws.SoftTokenSynDTO arg0) { 
        LOG.info("Executing operation performSoftTokenSync");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#getSoftTokenOnBoardingProcess(*
     */
    public com.expertedge.entrustplugin.ws.SoftTokenOnBoardingProcessResponseDTO getSoftTokenOnBoardingProcess() { 
        LOG.info("Executing operation getSoftTokenOnBoardingProcess");
        try {
            com.expertedge.entrustplugin.ws.SoftTokenOnBoardingProcessResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performReSendOTP(com.expertedge.entrustplugin.ws.OtpCreateSendDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performReSendOTP(com.expertedge.entrustplugin.ws.OtpCreateSendDTO arg0) { 
        LOG.info("Executing operation performReSendOTP");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performGetQA(com.expertedge.entrustplugin.ws.QaGetDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.QaGetResponseDTO performGetQA(com.expertedge.entrustplugin.ws.QaGetDTO arg0) { 
        LOG.info("Executing operation performGetQA");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.QaGetResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performTokenAuthCorporateNoCategory(com.expertedge.entrustplugin.ws.TokenAuthCorporateDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performTokenAuthCorporateNoCategory(com.expertedge.entrustplugin.ws.TokenAuthCorporateDTO arg0) { 
        LOG.info("Executing operation performTokenAuthCorporateNoCategory");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performGetMinQASize(com.expertedge.entrustplugin.ws.QaGetDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.QaSizeResponseDTO performGetMinQASize(com.expertedge.entrustplugin.ws.QaGetDTO arg0) { 
        LOG.info("Executing operation performGetMinQASize");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.QaSizeResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performSetMutualAuth2(com.expertedge.entrustplugin.ws.SetMutualSecretDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthMutResponseDTO performSetMutualAuth2(com.expertedge.entrustplugin.ws.SetMutualSecretDTO arg0) { 
        LOG.info("Executing operation performSetMutualAuth2");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthMutResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performAddContactDetail(com.expertedge.entrustplugin.ws.UserContactDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performAddContactDetail(com.expertedge.entrustplugin.ws.UserContactDTO arg0) { 
        LOG.info("Executing operation performAddContactDetail");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performMutualAuth(com.expertedge.entrustplugin.ws.MauthDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.ImageCaptionResponseDTO performMutualAuth(com.expertedge.entrustplugin.ws.MauthDTO arg0) { 
        LOG.info("Executing operation performMutualAuth");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.ImageCaptionResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performUnLockUser(com.expertedge.entrustplugin.ws.UserUnLockDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performUnLockUser(com.expertedge.entrustplugin.ws.UserUnLockDTO arg0) { 
        LOG.info("Executing operation performUnLockUser");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performCreateEntrustUser(com.expertedge.entrustplugin.ws.UserAdminDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performCreateEntrustUser(com.expertedge.entrustplugin.ws.UserAdminDTO arg0) { 
        LOG.info("Executing operation performCreateEntrustUser");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performActivateSoftToken(com.expertedge.entrustplugin.ws.ActivateSoftTokenDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.ActivateSoftTokenResponseDTO performActivateSoftToken(com.expertedge.entrustplugin.ws.ActivateSoftTokenDTO arg0) { 
        LOG.info("Executing operation performActivateSoftToken");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.ActivateSoftTokenResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performGetMutualAuth(com.expertedge.entrustplugin.ws.MauthDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.ImageCaptionResponseDTO performGetMutualAuth(com.expertedge.entrustplugin.ws.MauthDTO arg0) { 
        LOG.info("Executing operation performGetMutualAuth");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.ImageCaptionResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#pingEntrustConn(*
     */
    public java.lang.String pingEntrustConn() { 
        LOG.info("Executing operation pingEntrustConn");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performDeleteEntrustUser(com.expertedge.entrustplugin.ws.UserDelAdminDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performDeleteEntrustUser(com.expertedge.entrustplugin.ws.UserDelAdminDTO arg0) { 
        LOG.info("Executing operation performDeleteEntrustUser");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performPasswordAuth(com.expertedge.entrustplugin.ws.PasswordAuthDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performPasswordAuth(com.expertedge.entrustplugin.ws.PasswordAuthDTO arg0) { 
        LOG.info("Executing operation performPasswordAuth");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performIpGeoLocationAuth(com.expertedge.entrustplugin.ws.IpGeoAuthDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performIpGeoLocationAuth(com.expertedge.entrustplugin.ws.IpGeoAuthDTO arg0) { 
        LOG.info("Executing operation performIpGeoLocationAuth");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performUnassignToken(com.expertedge.entrustplugin.ws.TokenAdminDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performUnassignToken(com.expertedge.entrustplugin.ws.TokenAdminDTO arg0) { 
        LOG.info("Executing operation performUnassignToken");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performGetQASize(com.expertedge.entrustplugin.ws.QaGetDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.QaSizeResponseDTO performGetQASize(com.expertedge.entrustplugin.ws.QaGetDTO arg0) { 
        LOG.info("Executing operation performGetQASize");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.QaSizeResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performGetTokenSerial(com.expertedge.entrustplugin.ws.TokenSerialDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.TokenSerialResponseDTO performGetTokenSerial(com.expertedge.entrustplugin.ws.TokenSerialDTO arg0) { 
        LOG.info("Executing operation performGetTokenSerial");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.TokenSerialResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performCreateOTP(com.expertedge.entrustplugin.ws.OtpCreateDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performCreateOTP(com.expertedge.entrustplugin.ws.OtpCreateDTO arg0) { 
        LOG.info("Executing operation performCreateOTP");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AdminResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.expertedge.entrustplugin.ws.EntrustMultiFactorAuthImpl#performTokenAuth(com.expertedge.entrustplugin.ws.TokenAuthDTO  arg0 )*
     */
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performTokenAuth(com.expertedge.entrustplugin.ws.TokenAuthDTO arg0) { 
        LOG.info("Executing operation performTokenAuth");
        System.out.println(arg0);
        try {
            com.expertedge.entrustplugin.ws.AuthResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
