package com.expertedge.entrustplugin.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2018-06-21T22:11:01.766+01:00
 * Generated source version: 2.7.7
 * 
 * 
 */
@WebService(targetNamespace = "http://ws.entrustplugin.expertedge.com/", name = "EntrustMultiFactorAuthImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface EntrustMultiFactorAuthImpl { 

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateCompleteSoftTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateCompleteSoftTokenResponse")
    @RequestWrapper(localName = "performActivateCompleteSoftToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformActivateCompleteSoftToken")
    @ResponseWrapper(localName = "performActivateCompleteSoftTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformActivateCompleteSoftTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.ActivateCompleteSoftTokenResponseDTO performActivateCompleteSoftToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.ActivateCompleteSoftTokenDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeactivateTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeactivateTokenResponse")
    @RequestWrapper(localName = "performDeactivateToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformDeactivateToken")
    @ResponseWrapper(localName = "performDeactivateTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformDeactivateTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performDeactivateToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenAdminDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthResponse")
    @RequestWrapper(localName = "performSetMutualAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetMutualAuth")
    @ResponseWrapper(localName = "performSetMutualAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetMutualAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthMutResponseDTO performSetMutualAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.SetMutualSecretRespDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenSyncRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenSyncResponse")
    @RequestWrapper(localName = "performTokenSync", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenSync")
    @ResponseWrapper(localName = "performTokenSyncResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenSyncResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performTokenSync(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenSynDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performOTPAuthenticationRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performOTPAuthenticationResponse")
    @RequestWrapper(localName = "performOTPAuthentication", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformOTPAuthentication")
    @ResponseWrapper(localName = "performOTPAuthenticationResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformOTPAuthenticationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performOTPAuthentication(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.OtpAuthDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateTokenResponse")
    @RequestWrapper(localName = "performActivateToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformActivateToken")
    @ResponseWrapper(localName = "performActivateTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformActivateTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performActivateToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenAdminDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUpdateEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUpdateEntrustUserResponse")
    @RequestWrapper(localName = "performUpdateEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformUpdateEntrustUser")
    @ResponseWrapper(localName = "performUpdateEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformUpdateEntrustUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performUpdateEntrustUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.UserAdminDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSoftTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSoftTokenResponse")
    @RequestWrapper(localName = "performCreateSoftToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateSoftToken")
    @ResponseWrapper(localName = "performCreateSoftTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateSoftTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.CreateSoftTokenResponseDTO performCreateSoftToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.CreateSoftTokenDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthXRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthXResponse")
    @RequestWrapper(localName = "performSetMutualAuthX", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetMutualAuthX")
    @ResponseWrapper(localName = "performSetMutualAuthXResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetMutualAuthXResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthMutResponseDTO performSetMutualAuthX(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.SetMutualSecretXDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetQARequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetQAResponse")
    @RequestWrapper(localName = "performSetQA", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetQA")
    @ResponseWrapper(localName = "performSetQAResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetQAResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performSetQA(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.QaSetDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthNoCategoryRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthNoCategoryResponse")
    @RequestWrapper(localName = "performTokenAuthNoCategory", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthNoCategory")
    @ResponseWrapper(localName = "performTokenAuthNoCategoryResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthNoCategoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performTokenAuthNoCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenAuthDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAssignTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAssignTokenResponse")
    @RequestWrapper(localName = "performAssignToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformAssignToken")
    @ResponseWrapper(localName = "performAssignTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformAssignTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performAssignToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenAdminDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSendOTPRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSendOTPResponse")
    @RequestWrapper(localName = "performCreateSendOTP", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateSendOTP")
    @ResponseWrapper(localName = "performCreateSendOTPResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateSendOTPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performCreateSendOTP(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.OtpCreateSendDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSoftTokenSyncRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSoftTokenSyncResponse")
    @RequestWrapper(localName = "performSoftTokenSync", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSoftTokenSync")
    @ResponseWrapper(localName = "performSoftTokenSyncResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSoftTokenSyncResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performSoftTokenSync(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.SoftTokenSynDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/getSoftTokenOnBoardingProcessRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/getSoftTokenOnBoardingProcessResponse")
    @RequestWrapper(localName = "getSoftTokenOnBoardingProcess", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.GetSoftTokenOnBoardingProcess")
    @ResponseWrapper(localName = "getSoftTokenOnBoardingProcessResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.GetSoftTokenOnBoardingProcessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.SoftTokenOnBoardingProcessResponseDTO getSoftTokenOnBoardingProcess();

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performReSendOTPRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performReSendOTPResponse")
    @RequestWrapper(localName = "performReSendOTP", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformReSendOTP")
    @ResponseWrapper(localName = "performReSendOTPResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformReSendOTPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performReSendOTP(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.OtpCreateSendDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQARequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQAResponse")
    @RequestWrapper(localName = "performGetQA", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetQA")
    @ResponseWrapper(localName = "performGetQAResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetQAResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.QaGetResponseDTO performGetQA(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.QaGetDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthCorporateNoCategoryRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthCorporateNoCategoryResponse")
    @RequestWrapper(localName = "performTokenAuthCorporateNoCategory", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthCorporateNoCategory")
    @ResponseWrapper(localName = "performTokenAuthCorporateNoCategoryResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthCorporateNoCategoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performTokenAuthCorporateNoCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenAuthCorporateDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMinQASizeRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMinQASizeResponse")
    @RequestWrapper(localName = "performGetMinQASize", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetMinQASize")
    @ResponseWrapper(localName = "performGetMinQASizeResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetMinQASizeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.QaSizeResponseDTO performGetMinQASize(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.QaGetDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuth2Request", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuth2Response")
    @RequestWrapper(localName = "performSetMutualAuth2", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetMutualAuth2")
    @ResponseWrapper(localName = "performSetMutualAuth2Response", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformSetMutualAuth2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthMutResponseDTO performSetMutualAuth2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.SetMutualSecretDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAddContactDetailRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAddContactDetailResponse")
    @RequestWrapper(localName = "performAddContactDetail", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformAddContactDetail")
    @ResponseWrapper(localName = "performAddContactDetailResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformAddContactDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performAddContactDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.UserContactDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performMutualAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performMutualAuthResponse")
    @RequestWrapper(localName = "performMutualAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformMutualAuth")
    @ResponseWrapper(localName = "performMutualAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformMutualAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.ImageCaptionResponseDTO performMutualAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.MauthDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnLockUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnLockUserResponse")
    @RequestWrapper(localName = "performUnLockUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformUnLockUser")
    @ResponseWrapper(localName = "performUnLockUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformUnLockUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performUnLockUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.UserUnLockDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateEntrustUserResponse")
    @RequestWrapper(localName = "performCreateEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateEntrustUser")
    @ResponseWrapper(localName = "performCreateEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateEntrustUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performCreateEntrustUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.UserAdminDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateSoftTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateSoftTokenResponse")
    @RequestWrapper(localName = "performActivateSoftToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformActivateSoftToken")
    @ResponseWrapper(localName = "performActivateSoftTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformActivateSoftTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.ActivateSoftTokenResponseDTO performActivateSoftToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.ActivateSoftTokenDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMutualAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMutualAuthResponse")
    @RequestWrapper(localName = "performGetMutualAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetMutualAuth")
    @ResponseWrapper(localName = "performGetMutualAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetMutualAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.ImageCaptionResponseDTO performGetMutualAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.MauthDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/pingEntrustConnRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/pingEntrustConnResponse")
    @RequestWrapper(localName = "pingEntrustConn", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PingEntrustConn")
    @ResponseWrapper(localName = "pingEntrustConnResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PingEntrustConnResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String pingEntrustConn();

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeleteEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeleteEntrustUserResponse")
    @RequestWrapper(localName = "performDeleteEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformDeleteEntrustUser")
    @ResponseWrapper(localName = "performDeleteEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformDeleteEntrustUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performDeleteEntrustUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.UserDelAdminDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performPasswordAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performPasswordAuthResponse")
    @RequestWrapper(localName = "performPasswordAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformPasswordAuth")
    @ResponseWrapper(localName = "performPasswordAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformPasswordAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performPasswordAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.PasswordAuthDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performIpGeoLocationAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performIpGeoLocationAuthResponse")
    @RequestWrapper(localName = "performIpGeoLocationAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformIpGeoLocationAuth")
    @ResponseWrapper(localName = "performIpGeoLocationAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformIpGeoLocationAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performIpGeoLocationAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.IpGeoAuthDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnassignTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnassignTokenResponse")
    @RequestWrapper(localName = "performUnassignToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformUnassignToken")
    @ResponseWrapper(localName = "performUnassignTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformUnassignTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performUnassignToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenAdminDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQASizeRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQASizeResponse")
    @RequestWrapper(localName = "performGetQASize", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetQASize")
    @ResponseWrapper(localName = "performGetQASizeResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetQASizeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.QaSizeResponseDTO performGetQASize(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.QaGetDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetTokenSerialRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetTokenSerialResponse")
    @RequestWrapper(localName = "performGetTokenSerial", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetTokenSerial")
    @ResponseWrapper(localName = "performGetTokenSerialResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformGetTokenSerialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.TokenSerialResponseDTO performGetTokenSerial(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenSerialDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateOTPRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateOTPResponse")
    @RequestWrapper(localName = "performCreateOTP", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateOTP")
    @ResponseWrapper(localName = "performCreateOTPResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateOTPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AdminResponseDTO performCreateOTP(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.OtpCreateDTO arg0
    );

    @WebMethod
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthResponse")
    @RequestWrapper(localName = "performTokenAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuth")
    @ResponseWrapper(localName = "performTokenAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.expertedge.entrustplugin.ws.AuthResponseDTO performTokenAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        com.expertedge.entrustplugin.ws.TokenAuthDTO arg0
    );
}
